### ISSUE TITLE
Some error when interact with x-ray daemon

### ISSUE THREAD

**Issue by JerryZhao1988** [aws/aws-xray-sdk-python#109]
I met some problems when  using flask middleware and x-ray daemon.
I try to set up a local test environment with flask application and x-ray deamon running in my docker env.

I met some error logs when start flask service. Based on error msg, it becomes a little bit confuse, do I need to start segment myself when using flask middleware. Or this error is introduced by patch_all().
```
{"asctime": "2018-10-11 05:35:32,469", "name": "aws_xray_sdk.core.context", "funcName": "handle_context_missing", "threadName": "MainThread", "levelname": "ERROR", "lineno": 120, "message": "cannot find the current segment/subsegment, please make sure you have a segment open"}
{"asctime": "2018-10-11 05:35:32,471", "name": "aws_xray_sdk.core.recorder", "funcName": "begin_subsegment", "threadName": "MainThread", "levelname": "WARNING", "lineno": 273, "message": "No segment found, cannot begin subsegment https://xxxx.com/xxx/xxx/xxxx."}
```

When a request reached my flask service, I would met the following error msg
```
  File \"/usr/local/site-packages/aws_xray_sdk/core/sampling/rule_poller.py\", line 46, in _refresh_cache
    new_rules = self._connector.fetch_sampling_rules()
  File \"/usr/local/site-packages/aws_xray_sdk/core/sampling/connector.py\", line 42, in wrapper
    result = func(self, *args, **kargs)
  File \"/usr/local/site-packages/aws_xray_sdk/core/sampling/connector.py\", line 56, in fetch_sampling_rules
    resp = self._xray_client.get_sampling_rules()
  File \"/usr/local/site-packages/botocore/client.py\", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File \"/usr/local/site-packages/wrapt/wrappers.py\", line 562, in __call__
    args, kwargs)
  File \"/usr/local/site-packages/aws_xray_sdk/ext/botocore/patch.py\", line 35, in _xray_traced_botocore
    return wrapped(*args, **kwargs)
  File \"/usr/local/site-packages/botocore/client.py\", line 610, in _make_api_call
    operation_model, request_dict)
  File \"/usr/local/site-packages/botocore/endpoint.py\", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File \"/usr/local/site-packages/botocore/endpoint.py\", line 136, in _send_request
    success_response, exception):
  File \"/usr/local/site-packages/botocore/endpoint.py\", line 205, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File \"/usr/local/site-packages/botocore/hooks.py\", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File \"/usr/local/site-packages/botocore/hooks.py\", line 228, in emit
    return self._emit(event_name, kwargs)
  File \"/usr/local/site-packages/botocore/hooks.py\", line 211, in _emit
    response = handler(**kwargs)
  File \"/usr/local/site-packages/botocore/retryhandler.py\", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File \"/usr/local/site-packages/botocore/retryhandler.py\", line 251, in __call__
    caught_exception)
  File \"/usr/local/site-packages/botocore/retryhandler.py\", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File \"/usr/local/site-packages/botocore/retryhandler.py\", line 317, in __call__
    caught_exception)
  File \"/usr/local/site-packages/botocore/retryhandler.py\", line 223, in __call__
    attempt_number, caught_exception)
  File \"/usr/local/site-packages/botocore/retryhandler.py\", line 359, in _check_caught_exception
    raise caught_exception
  File \"/usr/local/site-packages/botocore/endpoint.py\", line 174, in _get_response
    http_response = self._send(request)
  File \"/usr/local/site-packages/botocore/endpoint.py\", line 218, in _send
    return self.http_session.send(request)
  File \"/usr/local/site-packages/botocore/httpsession.py\", line 262, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: \"http://aws-xray-daemon:2000/GetSamplingRules\""}
```

I manual tested the x-ray deamon server, it can send x-ray records to AWS, but I would keep getting this kind of error logs in my flask server, which is not good for monitoring. 
I try to deploy all those stack in AWS ECS, still get the same error.

I added flask middleware like this:
```
xray_recorder.configure(
    service='xxx',
    sampling_rules=sampling_rule,
    context_missing='LOG_ERROR',
    plugins=('ECSPlugin',)
)
patch_all()
XRayMiddleware(app, xray_recorder)
```

My x-ray daemon running in another docker container with following dockerfile
```
FROM amazonlinux:2
RUN yum install -y unzip &&\
    curl -o daemon.zip https://s3.dualstack.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-linux-2.x.zip &&\
    unzip daemon.zip &&\
    cp xray /usr/bin/xray
ADD src/xray-daemon.entrypoint.sh /opt/xray-daemon.entrypoint.sh
ADD src/xray-daemon.cfg           /opt/xray-daemon.cfg
ENTRYPOINT ["/opt/xray-daemon.entrypoint.sh"]
```

xray-daemon.cfg
```
TotalBufferSizeMB: 128
Concurrency: 4
Region: xxxx
Socket:
  UDPAddress: "0.0.0.0:2000"
Logging:
  LogLevel: "error"
  LogPath: ""
LocalMode: true

ProxyAddress: "##PROXY_ADDRESS##"
Version: 1
```
entrypoint.sh 
```
#!/usr/bin/env bash
declare -r XRAY_DAEMON_CONF="/opt/xray-daemon.cfg"
declare -r CMD="/usr/bin/xray --bind 0.0.0.0:2000 -c ${XRAY_DAEMON_CONF}"
echo "### Starting Daemon with CMD [${CMD}] ###"
exec ${CMD}
```

docker-compose.yml
```
version: 2.1
services:
    flask-service:
        environment:
            AWS_XRAY_DAEMON_ADDRESS: 'aws-xray-daemon:2000'
        xxxx:
    aws-xray-daemon:
        environment:
            AWS_REGION: xxx
            AWS_DEFAULT_REGION: xxx
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
            AWS_SECURITY_TOKEN: ${AWS_SECURITY_TOKEN}
        command:
            - "/usr/bin/xray"
            - "--bind"
            - "0.0.0.0:2000"
            - "--region"
            - "xxx"
            - "--buffer-memory"
            - "64"
            - "--log-level"
            - dev
            - "--log-file"
            - "/dev/stdout"
```

dependency:
```
Flask==0.12.2

# x-ray
aws-xray-sdk==2.2.0
tox==3.4.0

boto==2.49.0
boto3==1.9.12
requests==2.18.4
```
